In [1]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 8.4 MB/s eta 0:00:0000:0100:01m

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip


In [2]:
pip install --upgrade pip

  Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Note: you may need to restart the kernel to use updated packages.


In [3]:
!pip install numpy

In [9]:
import numpy as np

In [12]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [13]:
data

array([[[0.15082975, 0.71561   , 0.20521998, 0.85302256],
        [0.13817657, 0.80285496, 0.73427375, 0.60039434],
        [0.84751426, 0.82074976, 0.88720419, 0.91283508]],

       [[0.68046411, 0.04962999, 0.03077996, 0.76815254],
        [0.20495401, 0.53141242, 0.52354156, 0.57130421],
        [0.81888181, 0.09969306, 0.56024502, 0.1593117 ]]])

In [14]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [16]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [18]:
arr = np.array([[1,2,3,4], [1,2,3,4]])

# Read

In [20]:
#Attributes
shape = data.shape
size = data.size
types = data.dtype

In [21]:
types

dtype('float64')

In [22]:
#slicing
arr = data[0]
slicer = data[0,2]
reverse = data[-1]
level = data[0][0][0]

In [23]:
level

0.15082974623961898

# Update