In [1]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 8.4 MB/s eta 0:00:0000:0100:01m

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip


In [2]:
pip install --upgrade pip

  Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Note: you may need to restart the kernel to use updated packages.


In [3]:
!pip install numpy

In [3]:
import numpy as np

In [12]:
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [13]:
data

array([[[0.15082975, 0.71561   , 0.20521998, 0.85302256],
        [0.13817657, 0.80285496, 0.73427375, 0.60039434],
        [0.84751426, 0.82074976, 0.88720419, 0.91283508]],

       [[0.68046411, 0.04962999, 0.03077996, 0.76815254],
        [0.20495401, 0.53141242, 0.52354156, 0.57130421],
        [0.81888181, 0.09969306, 0.56024502, 0.1593117 ]]])

In [14]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [16]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [18]:
arr = np.array([[1,2,3,4], [1,2,3,4]])

# Read

In [20]:
#Attributes
shape = data.shape
size = data.size
types = data.dtype

In [21]:
types

dtype('float64')

In [22]:
#slicing
arr = data[0]
slicer = data[0,2]
reverse = data[-1]
level = data[0][0][0]

In [23]:
level

0.15082974623961898

# Tutorial 2

In [16]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [11]:
b = np.array([[1,2,3,4,5],[1,2,2,3,4]])
print (b)

[[1 2 3 4 5]
 [1 2 2 3 4]]


In [12]:
a.ndim

1

b.shape

In [13]:
b.shape

(2, 5)

In [17]:
#Get Type
a.dtype

dtype('int32')

In [18]:
#Get size
a.itemsize

4

In [20]:
a.size * a.itemsize

12

In [21]:
a.nbytes

12

In [23]:
b.nbytes

80

In [25]:
data = np.random.rand(2,7)

In [26]:
print(data)

[[0.78862559 0.65593651 0.76551234 0.42748832 0.80418961 0.59190605
  0.87170833]
 [0.62537928 0.16269243 0.24845096 0.28949106 0.63074999 0.43783457
  0.39169804]]


In [27]:
data[1,5]

0.4378345714569388

In [29]:
data[1,-2]

0.4378345714569388

In [31]:
# Get a specific row
data[0, :]

array([0.78862559, 0.65593651, 0.76551234, 0.42748832, 0.80418961,
       0.59190605, 0.87170833])

In [32]:
#Get a specific column
data[:,2]

array([0.76551234, 0.24845096])

In [33]:
#More Fancy [start_index:end_index: stepsize]
data[0,1: 6 : 2]

array([0.65593651, 0.42748832, 0.59190605])

In [38]:
data [0,1] = int(40)
print (data)

[[ 0.78862559 40.          0.76551234  0.42748832  0.80418961  0.59190605
   0.87170833]
 [ 0.62537928  0.16269243  0.24845096  0.28949106  0.63074999  0.43783457
   0.39169804]]


In [43]:
data

array([[-1173417845,  1072249963,           0,  1078198272, -1121994871,
         1072201491,  -108626854,  1071340535,  -631998482,  1072282603,
         -149187585,  1071837412,  -582674295,  1072424200],
       [ 1757943973,  1071907611,   125505860,  1069863707, -1418168164,
         1070583101, -2071485390,  1070761733, -1740054704,  1071918874,
         1264438906,  1071383931, -1550908150,  1071190420]], dtype=int32)

In [40]:
data.dtype = 'int32'

In [41]:
data

array([[-1173417845,  1072249963,           0,  1078198272, -1121994871,
         1072201491,  -108626854,  1071340535,  -631998482,  1072282603,
         -149187585,  1071837412,  -582674295,  1072424200],
       [ 1757943973,  1071907611,   125505860,  1069863707, -1418168164,
         1070583101, -2071485390,  1070761733, -1740054704,  1071918874,
         1264438906,  1071383931, -1550908150,  1071190420]], dtype=int32)

In [42]:
print (data)

[[-1173417845  1072249963           0  1078198272 -1121994871  1072201491
   -108626854  1071340535  -631998482  1072282603  -149187585  1071837412
   -582674295  1072424200]
 [ 1757943973  1071907611   125505860  1069863707 -1418168164  1070583101
  -2071485390  1070761733 -1740054704  1071918874  1264438906  1071383931
  -1550908150  1071190420]]


In [44]:
data = np.random.randint(-4,22, size = (3,3))

In [45]:
data

array([[19, 13,  5],
       [-2, -3, 21],
       [ 0, -1, 10]])

In [46]:
arr = np.array([[1,2,3]]) #Have to make it a double
r1 = np.repeat(arr, 3, axis = 0) #axis 0 is rows, axis 1 is columns
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [50]:
output = np.full((5,5), 1, dtype = 'int32')
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [51]:
output.dtype

dtype('int32')

In [61]:
zero = np.zeros((3,3))
zero [1,1] = 9

output[1:4,1:4] = zero

ValueError: could not broadcast input array from shape (3,3) into shape (3,5)

In [62]:
print (output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [66]:
d = output.copy()
d[1,2] = 13245
d

array([[    1,     1,     1,     1,     1],
       [    1,     0, 13245,     0,     1],
       [    1,     0,     9,     0,     1],
       [    1,     0,     0,     0,     1],
       [    1,     1,     1,     1,     1]], dtype=int32)

# Arithmetics

In [83]:
a = np.array([1,2,3,4])
#a.dtype = 'int32'
a += 2 ## adds 2 to every element
a

array([3, 4, 5, 6])

In [69]:
a

array([3, 4, 5, 6])

In [70]:
a -= 2

In [71]:
a

array([1, 2, 3, 4])

In [85]:
a ** 2

array([ 9, 16, 25, 36])

In [81]:
a.dtype

dtype('int32')

In [84]:
a

array([3, 4, 5, 6])

In [86]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

### Linear Algebra

In [90]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# For Linear Algebra, column of first matched row of second

[[1. 1. 1.]
 [1. 1. 1.]]


array([[2, 2],
       [2, 2],
       [2, 2]])

In [91]:
np.matmul(a,b) #What is matric multiplication

array([[6., 6.],
       [6., 6.]])

In [92]:
#Find the Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [102]:
stats = np.array([[1,2,3], [4,7,6]])
stats

array([[1, 2, 3],
       [4, 7, 6]])

In [103]:
np.min(stats, axis = 1)

array([1, 4])

In [104]:
np.sum(stats)

23

## Reorganizing Arrays

In [108]:
dat = np.array([[1,2,3], [4,7,6]])
print (dat)

afterDat = dat.reshape((6,1))
afterDat

[[1 2 3]
 [4 7 6]]


array([[1],
       [2],
       [3],
       [4],
       [7],
       [6]])

In [109]:
stack = dat.copy()
stacks = np.vstack([dat,stack])
stacks

array([[1, 2, 3],
       [4, 7, 6],
       [1, 2, 3],
       [4, 7, 6]])